#ifndef OPCODES_H
#define OPCODES_H

enum op_code : unsigned char
{
    NO_OP = 0x00,
    LOAD_BC_FROM_MEMORY = 0x01,
    LOAD_A_INTO_BC_POINTER = 0x02,
    INCREMENT_BC = 0x03,
    INCREMENT_B = 0x04,
    DECREMENT_B = 0x05,
    LOAD_B_FROM_MEMORY = 0x06,
    ROTATE_A_LEFT = 0x07,
    LOAD_SP_INTO_POINTER = 0x08,
    ADD_BC_TO_HL = 0x09,
    LOAD_BC_POINTER_INTO_A = 0x0A,
    DECREMENT_BC = 0x0B,
    INCREMENT_C = 0x0C,
    DECREMENT_C = 0x0D,
    LOAD_C_FROM_MEMORY = 0x0E,
    ROTATE_A_RIGHT = 0x0F,
    STOP = 0x10,
    LOAD_DE_FROM_MEMORY = 0x11,
    LOAD_A_INT_DE_POINTER = 0x12,
    JUMP_IF_Z_IS_ZERO = 0x20,
    LOAD_HL_FROM_MEMORY = 0x21,
    LOAD_SP_FROM_MEMORY = 0x31,
    LOAD_A_INTO_HL_CONTENTS_AND_DECREMENT_HL = 0x32,
    SUBTRACT_C_INTO_A = 0x9F,
    XOR_A = 0xAF,
    JUMP = 0xC3,
    USE_EXTENDED_OP_CODE = 0xCB,
    LOAD_A_FROM_LOW_POINTER = 0xF0,
    DISABLE_IME = 0xF3,
    LOAD_A_FROM_POINTER = 0xFA,
    COMPARE_A_TO_MEMORY = 0xFE
};

enum extended_op_code
{
    COPY_INVERSE_BIT_7_H_TO_Z = 0x7C
};

#endif //OPCODES_H
